"""
Multiples of 3 and 5:
    If we list all the natural numbers below that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    what is the sum of all multiples of 3 or 5 below 1000
"""


def multiples_three_five(bounds, a, b):
    total = 0
    for i in range(bounds):
        if i % a == 0 or i % b == 0:
            total += i
    return total


"""
Even Fibonacci Numbers:
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def even_fibonacci(bounds):
    a, b = 1, 2  # first two numbers
    total = 0
    while a <= bounds:
        if a % 2 == 0:
            total += a
        a, b = b, a + b
    return total


if __name__ == "__main__":
    print(multiples_three_five(1000, 3, 5))
    print(even_fibonacci(4000000))
